export const YOSHI_ENDPOINT = "http://yoshi:3000";

export const REQUIRED_ENV_VARS = [
	"USER_CREATE_TOKEN",
	"USER_UPDATE_TOKEN",
	"USER_ALUMNIZE_TOKEN",
	"TEAM_CREATE_TOKEN",
	"SCALE_TEAM_CREATE_TOKEN",
	"SCALE_TEAM_UPDATE_TOKEN",
	"SCALE_TEAM_DESTROY_TOKEN",
	"LOCATION_CREATE_TOKEN",
	"LOCATION_CLOSE_TOKEN",
] as const;
